### ISSUE TITLE
#US08 Como usuario comensal me gustaría que los precios figuren en cada producto para saber cuánto salen.

### ISSUE THREAD

**Issue by ezefalzoi** [IgnacioCarnero/ISPC-KillCode-AplicacionesMoviles#15]

**Comment by Romherre** [comment]
- [ ] Las vistas que integran los menús de alimentos y bebidas deben incluir el precio de cada ítem.

**Comment by Romherre** [comment]
- [ ] Incluir una card / banner que describa los medios de pago disponible en la vista del carrito, con la finalidad que el usuario vea los medios de pago disponibles.

**Comment by Leo-Farran** [comment]
Campo "precio" incluido en la tabla comidaBebida, además este dato se consulta a la base de datos y se presenta en la vista MenuScroll/fragment
