### ISSUE TITLE
#US10 Como usuario cliente me gustaría tener una app en cada mesa para que los comensales realicen su pedido.

### ISSUE THREAD

**Issue by ezefalzoi** [IgnacioCarnero/ISPC-KillCode-AplicacionesMoviles#17]

**Comment by Romherre** [comment]
- [ ] Se debe crear un usuario “comensal” con la finalidad de que cada mesa tenga un dispositivo móvil (tablet) donde el comensal interactúa con la aplicación. El usuario cliente puede configurar y habilitar usuarios comensal según la cantidad de mesas disponibles.

**Comment by Leo-Farran** [comment]
La aplicación puede distribuirse a través de su compilación en formato de archivo .apk
